### ISSUE TITLE
make the function `createICS` exposed

### ISSUE THREAD

**Issue by yudukikun5120** [Mimori256/twinc#8]
I'm planning to create the CLI of the function of this repo, so I want the function `createICS` and its dependencies to be exposed.

The architecture I'm thinking of are:
- make them independent repo and this repo use it as a Git submodule
- make them independent repo as a NodeJS package (registration for a registree is not necessary)

I would appreciate your consideration.

**Comment by Mimori256** [comment]
okay, feel free to do that!!
but keep in mind that the code is under the GPL v3

**Comment by yudukikun5120** [comment]
@Mimori256
I appreciate your consideration and kind permission. I think the first plan(creating a submodule repository) is good enough because creating a NodeJS package spends some effort (writing `package.json` etc.) and just copying the codes is not good practice in keeping consistency to the logic changes. The diagram below shows how it'll be constituted.

```mermaid
graph TD
    React & CLI --> submodule
```

I'd list some tasks to achieve this plan.
- [x] @yudukikun5120 creates the submodule repo including the function `createICS` and its dependencies and transfers it to @Mimori256.
- [x] @yudukikun5120 creates the PR making the change for this repo to use the submodule repo.
- [ ] I'll create the CLI tool of TwinC after it's merged.

**Comment by yudukikun5120** [comment]
@Mimori256 I requested that the repo ([twinc-core](https://github.com/yudukikun5120/twinc-core)) be transferred to you and I kindly ask you to accept it.

**Comment by Mimori256** [comment]
I'd love to do that but seems like I haven't got any notification concerning the transfer so I can't do that now...

**Comment by Mimori256** [comment]
@yudukikun5120  sry there was in my spam folder... I clicked the link but it said the link was expired already. could you send me the request again?

**Comment by yudukikun5120** [comment]
@Mimori256 I did it. Can you check it?

**Comment by Mimori256** [comment]
@yudukikun5120  I did!
